version: '3.2'
services:

  dump1090:
    build: ./dump1090
    restart: always
    container_name: dump1090
    privileged: true
    ports:
     - "8080:8080"
     - "30005:30005"
    environment:
      - PIAWARE_LAT=38.923440
      - PIAWARE_LON=-77.325390
    devices:
      - /dev/bus/usb:/dev/bus/usb

  piaware:
    container_name: piaware
    restart: always
    build: ./flightaware
    environment:
      - PIAWARE_HOST=dump1090
      - PIAWARE_PORT=30005
      - PIAWARE_FEEDER_ID=db694712-8509-4a4d-98c7-891c180552db
