version: '3.2'
services:

  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    ports:
      - 8080:8080
    volumes:
      - data-volume:/data

  dump1090:
    build: ./dump1090
    restart: always
    container_name: dump1090
    privileged: true
    ports:
     - 30003
     - 30004
     - 30005
     - 30104
    environment:
      - PIAWARE_LAT=38.923440
      - PIAWARE_LON=-77.325390
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - data-volume:/run/dump1090-fa/

  piaware:
    build: ./piaware
    container_name: piaware
    restart: always
    environment:
      - PIAWARE_HOST=dump1090
      - PIAWARE_PORT=30005
      - PIAWARE_MLAT_PORT=30104
      - PIAWARE_FEEDER_ID=db694712-8509-4a4d-98c7-891c180552db

volumes:
  data-volume: {}
