version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging in to Docker Hub
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker image build -t arhea/flightaware-base:$IMAGE_TAGE ./flightaware

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image push arhea/flightaware-base:$IMAGE_TAGE
